/* Enterprise email communications. Local intent collection; the model cannot send anything.
   Telephone calling and SMS were removed permanently — email is the only channel. */
(() => {
'use strict';
const q=s=>document.querySelector(s);
const allowed=()=>window.OraCommunicationsAccess?.()===true;
const sheet=document.createElement('dialog');sheet.id='commsSheet';sheet.className='settings-sheet';sheet.setAttribute('aria-label','Communications');
sheet.innerHTML=`<div class="sheet-head"><div><span class="sheet-eyebrow">ENTERPRISE WORKSPACE</span><h2>Communications</h2></div><button class="btn ghost" id="commsClose" aria-label="Close communications">✕</button></div>
<div class="sheet-body"><div id="commsLocked" class="comms-locked" hidden><h3>Your words.<br>A confirmed action.</h3><p>Outbound email is available with Enterprise or administrator access. Operator setup and recipient consent are required.</p><button class="btn primary" id="commsUpgrade">Explore Enterprise · $500</button></div>
<div id="commsForm" hidden>
<div id="commsStatus" class="comms-status" role="status">Checking email setup…</div>
<p class="hint" id="commsHint">Email uses the operator’s verified SendGrid sender—not your signed-in Gmail address. Transactional messages only; no bulk marketing. Telephone calling and SMS are not available on OraCool.</p>
<label class="comms-field">Recipient email<input id="commsTo" type="email" autocomplete="off" placeholder="recipient@example.com"></label>
<label class="comms-field">Subject<input id="commsSubject" type="text" maxlength="160" value="A message from OraCool"></label>
<label class="comms-field"><span>Message</span><textarea id="commsMessage" maxlength="4000" placeholder="Write the exact message to send…"></textarea></label>
<button class="btn primary" id="commsReview">Review message</button><div id="commsReviewBox" aria-live="polite"></div>
<details id="commsVerification"><summary>Verify a consenting recipient</summary><p class="hint">Use the destination above. The recipient must control the address and agree to this verification and your messages. Verification sends a one-time code to the address itself. Never paste verification codes into chat. Recipients are verified for 30 days.</p><label><input id="commsConsent" type="checkbox"> This recipient controls the address and has agreed to verification and the communications I request.</label><div class="row" style="margin:12px 0"><button class="btn ghost" id="commsSendCode">Send verification code</button><input id="commsCode" autocomplete="one-time-code" inputmode="numeric" placeholder="Verification code" style="width:145px"><button class="btn ghost" id="commsCheckCode">Verify recipient</button></div><div id="commsVerifyStatus" class="hint" role="status"></div></details>
<details><summary>Verified recipients</summary><div id="commsContacts"></div></details><details><summary>Recent activity</summary><button class="btn ghost" id="commsRefresh">Refresh status</button><div id="commsHistory"></div></details>
<p class="hint" style="margin-top:20px">Single-recipient, consensual transactional messages only. Maximum 10 sends per account and 5 per recipient per day, plus platform limits. Provider credit applies. Provider acceptance is not delivery confirmation.</p></div></div>`;
document.body.appendChild(sheet);
let currentOwner='',pending=null,draft=null,verificationId='',snapshot=null,sending=false,requestEpoch=0;
function reply(text){addAI(text);speak(text);saveChat();}
function reset(){requestEpoch++;pending=null;draft=null;verificationId='';snapshot=null;q('#commsTo').value='';q('#commsMessage').value='';q('#commsCode').value='';q('#commsConsent').checked=false;q('#commsSubject').value='A message from OraCool';['commsReviewBox','commsVerifyStatus','commsContacts','commsHistory'].forEach(id=>q('#'+id).textContent='');q('#commsStatus').textContent='Open Communications to check setup.';}
function access(){const owner=session?.access_token?(myEmail()+'|'+allowed()):'';if(owner!==currentOwner){reset();currentOwner=owner;}q('#commsLocked').hidden=allowed();q('#commsForm').hidden=!allowed();}
function open(){access();if(window.OraSettings)window.OraSettings.close();if(!sheet.open)sheet.showModal();if(allowed())refresh();}
function showStatus(){const cfg=snapshot?.config?.email;const el=q('#commsStatus');el.className='comms-status '+(cfg?.ready?'good':'warn');el.textContent=cfg?(cfg.ready?'Email provider configured. Verify your recipient, review the exact message, then confirm.':'Not enabled yet. Operator setup needed: '+(cfg.missing||[]).join(', ')+'. You can still prepare a preview; nothing will be sent.'):'Open or refresh this drawer to check setup.';q('#commsSendCode').disabled=!cfg?.ready;q('#commsCheckCode').disabled=!cfg?.ready;}
async function refresh(){if(!allowed())return;const owner=myEmail(),epoch=requestEpoch;try{const r=await post('/api/comms/state',{});if(owner!==myEmail()||epoch!==requestEpoch||!allowed())return;if(r.error){q('#commsStatus').textContent=r.error;return;}snapshot=r;showStatus();q('#commsContacts').innerHTML=(r.contacts||[]).map(c=>`<div class="comms-row"><button class="btn ghost" data-remove="${escapeHtml(c.id)}">Remove</button>${escapeHtml(c.mask)} · ${escapeHtml(c.type)}</div>`).join('')||'<p class="hint">No verified recipients yet.</p>';q('#commsHistory').innerHTML=(r.messages||[]).map(c=>`<div class="comms-row">${escapeHtml(c.channel.toUpperCase())} · ${escapeHtml(c.recipient)}<br><b>${escapeHtml(c.status)}</b> · ${escapeHtml(new Date(c.created*1000).toLocaleString())}</div>`).join('')||'<p class="hint">No send attempts yet.</p>';q('#commsContacts').querySelectorAll('[data-remove]').forEach(b=>b.onclick=async()=>{if(!confirm('Remove this recipient and invalidate unconfirmed drafts?'))return;const x=await post('/api/comms/remove',{id:b.dataset.remove});if(x.error)q('#commsStatus').textContent=x.error;else{invalidate();refresh();}});}catch(e){q('#commsStatus').textContent='Could not check provider/storage status. Nothing new was sent.';}}
function payload(){return {channel:'email',to:q('#commsTo').value.trim(),message:q('#commsMessage').value.trim(),subject:q('#commsSubject').value.trim()};}
function invalidate(){requestEpoch++;draft=null;q('#commsReviewBox').textContent='';}
async function review(inChat=false){if(!allowed())return;const owner=myEmail(),epoch=requestEpoch,body=payload();q('#commsReview').disabled=true;draft=null;try{const r=await post('/api/comms/preview',body);if(owner!==myEmail()||epoch!==requestEpoch||!allowed())return;if(r.error){q('#commsReviewBox').textContent=r.error;if(inChat)reply(r.error);return;}draft=r.draft_id?{id:r.draft_id,owner,expires:Date.now()+120000,channel:'email'}:null;const blocked=!r.ready?'Provider setup is incomplete. No send is possible.':!r.verified?'Verify this consenting recipient, then review again.':'';q('#commsReviewBox').innerHTML=`<div class="comms-review"><span class="sheet-eyebrow">REVIEW · EMAIL</span><p class="to">To: ${escapeHtml(r.to)}</p><b>${escapeHtml(r.subject||'')}</b><pre>${escapeHtml(r.message)}</pre><p class="hint">${escapeHtml(r.note)}</p>${blocked?'<p class="hint">'+escapeHtml(blocked)+'</p>':'<p class="hint">Preview expires in two minutes. Confirming uses provider credit.</p><div class="row"><button class="btn primary" id="commsConfirm">Confirm send</button><button class="btn ghost" id="commsCancel">Cancel</button></div>'}</div>`;if(draft){q('#commsConfirm').onclick=()=>confirmSend();q('#commsCancel').onclick=()=>{invalidate();pending=null;reply('Cancelled before sending.');};}else if(!r.verified)q('#commsVerification').open=true;if(inChat)reply('I prepared the email to '+r.to+'. '+(blocked||'Review the exact message in Communications. Say “confirm send” or use the confirmation button. Nothing has been sent yet.'));}catch(e){q('#commsReviewBox').textContent='Preview unavailable. Nothing has been sent.';}finally{q('#commsReview').disabled=false;}}
async function confirmSend(){if(sending)return;if(!allowed()||!draft||draft.owner!==myEmail()){reply('Open Communications and review a message before confirming.');return;}if(draft.expires<Date.now()){invalidate();reply('The preview expired. Please review again.');return;}const d=draft,owner=myEmail();sending=true;const btn=q('#commsConfirm');if(btn)btn.disabled=true;try{const r=await post('/api/comms/send',{draft_id:d.id,confirmed:true});if(owner!==myEmail()||!allowed())return;reply(r.error||r.message||('Provider status: '+r.status));q('#commsReviewBox').textContent=r.error||r.message||('Status: '+r.status);draft=null;pending=null;refresh();}catch(e){if(owner===myEmail()){draft=null;q('#commsReviewBox').textContent='Outcome uncertain. Refresh activity and check the provider console before any new attempt. No automatic retry.';reply(q('#commsReviewBox').textContent);}}finally{sending=false;}}
q('#commsClose').onclick=()=>sheet.close();q('#commsToggle').onclick=open;q('#commsUpgrade').onclick=()=>{sheet.close();openUpgrade('enterprise');};
q('#commsReview').onclick=()=>review();q('#commsRefresh').onclick=refresh;
['commsTo','commsMessage','commsSubject'].forEach(id=>q('#'+id).addEventListener('input',()=>{invalidate();pending=null;verificationId='';q('#commsCode').value='';q('#commsConsent').checked=false;}));
q('#commsSendCode').onclick=async()=>{const owner=myEmail(),epoch=requestEpoch;const b=payload();q('#commsSendCode').disabled=true;try{const r=await post('/api/comms/verify/send',{channel:b.channel,to:b.to,consent:q('#commsConsent').checked});if(owner!==myEmail()||epoch!==requestEpoch)return;verificationId=r.verification_id||'';q('#commsVerifyStatus').textContent=r.error||r.message;}catch(e){q('#commsVerifyStatus').textContent='Verification outcome uncertain. Wait before retrying.';}finally{showStatus();}};
q('#commsCheckCode').onclick=async()=>{if(!verificationId){q('#commsVerifyStatus').textContent='Request a code for this destination first.';return;}const owner=myEmail(),epoch=requestEpoch,code=q('#commsCode').value.trim();q('#commsCode').value='';q('#commsCheckCode').disabled=true;try{const r=await post('/api/comms/verify/check',{verification_id: verificationId, code});if(owner!==myEmail()||epoch!==requestEpoch)return;q('#commsVerifyStatus').textContent=r.error||'Recipient verified. Review the message again before sending.';if(!r.error){invalidate();refresh();}}catch(e){q('#commsVerifyStatus').textContent='Verification unavailable. Nothing has been sent.';}finally{showStatus();}};
window.OraComms={open,async handle(text){access();const clean=text.trim();
if(pending&&pending.owner!==myEmail())pending=null;
if((pending||draft)&&/^(?:cancel(?: send| email| message)?|never mind|nevermind|no)[.!]?$/i.test(clean)){addUser(text);pending=null;invalidate();reply('Cancelled. Nothing new was sent.');return true;}
if(draft&&/^(?:confirm (?:send|email|message))[.!]?$/i.test(clean)){addUser(text);await confirmSend();return true;}
if(pending?.stage==='message'){addUser(text);q('#commsMessage').value=clean;pending=null;open();await review(true);return true;}
const command=clean.replace(/^(?:hey\s+)?ora[\s-]?cool[,]\s*/i,'');
const m=command.match(/^(?:email|send\s+an?\s+email(?:\s+to)?)\s+(?:to\s+)?([^@\s]+@[^@\s]+\.[^@\s]+?)(?:\s+(?:and\s+)?(?:say|saying|tell\s+(?:them|him|her)|with\s+(?:the\s+)?message|message)\s*:\s*([\s\S]+))?\s*$/i);
if(!m)return false;addUser(text);if(!allowed()){reply('Email requires Enterprise or administrator access. Normal hands-free voice remains available.');open();return true;}
q('#commsTo').value=m[1].trim();q('#commsMessage').value=m[2]||'';
if(m[2]){open();await review(true);}else{pending={stage:'message',owner:myEmail()};reply('What message should I send? I will prepare a review before sending.');}
return true;}};
setInterval(access,500);access();
// Pricing links survive the sign-in gate without starting checkout or charging anything.
let chosen=new URLSearchParams(location.search).get('plan');if(!['starter','pro','ultra','enterprise'].includes(chosen))chosen='';
if(chosen){const timer=setInterval(()=>{if(session?.access_token&&!q('#authGate')?.classList.contains('open')&&srv?.plans){clearInterval(timer);openUpgrade(chosen);const u=new URL(location.href);u.searchParams.delete('plan');history.replaceState({},'',u.pathname+u.search+u.hash);}},700);}
})();
