# OraCool AI cores 801-1000 (Clusters 9-10). (num, name, role, example)
PART4 = [
(801,"DESIGN","Design Intelligence","Design a logo for my brand"),
(802,"UI","UI Design","Design a user interface"),
(803,"UX","UX Design","Improve user experience"),
(804,"GRAPHIC","Graphic Design","Create a graphic"),
(805,"BRANDING","Branding","Develop a brand identity"),
(806,"LOGO","Logo Design","Design a logo"),
(807,"PACKAGING","Packaging Design","Design packaging"),
(808,"MOTION","Motion Graphics","Create motion graphics"),
(809,"3D","3D Modeling","Create a 3D model"),
(810,"ANIMATION","Animation","Create an animation"),
(811,"MUSIC_COMPOSE","Music Composition","Compose a song"),
(812,"MUSIC_PRODUCE","Music Production","Produce a track"),
(813,"SOUND_DESIGN","Sound Design","Design a sound"),
(814,"AUDIO_EDIT","Audio Editing","Edit audio"),
(815,"MIXING","Audio Mixing","Mix audio"),
(816,"MASTERING","Audio Mastering","Master audio"),
(817,"VOICE","Voice Production","Produce voiceover"),
(818,"PODCAST","Podcast Production","Produce a podcast"),
(819,"RADIO","Radio Production","Produce radio content"),
(820,"MUSIC_ANALYSIS","Music Analysis","Analyze this song"),
(821,"VIDEO_PROD","Video Production","Produce a video"),
(822,"FILM","Film Production","Produce a film"),
(823,"DIRECT","Directing","Direct a scene"),
(824,"CINEMA","Cinematography","Cinematography advice"),
(825,"EDIT","Video Editing","Edit video"),
(826,"VFX","Visual Effects","Add VFX"),
(827,"ANIMATION","Animation","Animate a scene"),
(828,"SCRIPT","Scriptwriting","Write a script"),
(829,"STORYBOARD","Storyboarding","Create a storyboard"),
(830,"FILM_ANALYSIS","Film Analysis","Analyze this film"),
(831,"WRITING","Creative Writing","Write a story"),
(832,"POETRY","Poetry","Write a poem"),
(833,"FICTION","Fiction Writing","Write a novel"),
(834,"NONFICTION","Non-Fiction Writing","Write a non-fiction piece"),
(835,"JOURNALISM","Journalism","Write a news article"),
(836,"BLOG","Blog Writing","Write a blog post"),
(837,"COPY","Copywriting","Write copy"),
(838,"EDITING","Editing","Edit text"),
(839,"PROOF","Proofreading","Proofread text"),
(840,"LITERARY","Literary Analysis","Analyze a text"),
(841,"PHOTOGRAPHY","Photography","Take a photo"),
(842,"PHOTO_EDIT","Photo Editing","Edit a photo"),
(843,"PHOTOGRAPHY_ANALYSIS","Photo Analysis","Analyze a photo"),
(844,"PHOTOGRAPHY_COMPOSITION","Composition","Compose a photo"),
(845,"PHOTOGRAPHY_LIGHTING","Lighting","Light a scene"),
(846,"PHOTOGRAPHY_COLOR","Color Theory","Use color theory"),
(847,"PHOTOGRAPHY_PORTRAIT","Portrait Photography","Take a portrait"),
(848,"PHOTOGRAPHY_LANDSCAPE","Landscape Photography","Take a landscape photo"),
(849,"PHOTOGRAPHY_WILDLIFE","Wildlife Photography","Take a wildlife photo"),
(850,"PHOTOGRAPHY_STREET","Street Photography","Take a street photo"),
(851,"FASHION","Fashion Design","Design a fashion collection"),
(852,"STYLE","Style Analysis","Analyze this style"),
(853,"WARDROBE","Wardrobe Planning","Plan a wardrobe"),
(854,"ACCESSORIES","Accessory Design","Design accessories"),
(855,"FASHION_TREND","Fashion Trends","Identify fashion trends"),
(856,"FASHION_HISTORY","Fashion History","Explain fashion history"),
(857,"FASHION_BRAND","Fashion Branding","Build a fashion brand"),
(858,"FASHION_ECOMMERCE","Fashion E-commerce","Sell fashion online"),
(859,"FASHION_MODELING","Fashion Modeling","Model fashion"),
(860,"FASHION_PHOTOGRAPHY","Fashion Photography","Photograph fashion"),
(861,"ARCHITECTURE","Architecture","Design a building"),
(862,"INTERIOR","Interior Design","Design an interior"),
(863,"LANDSCAPE","Landscape Architecture","Design a landscape"),
(864,"URBAN","Urban Planning","Plan a city"),
(865,"SUSTAINABLE","Sustainable Design","Design sustainably"),
(866,"HISTORICAL","Historical Architecture","Explain historical architecture"),
(867,"MODERN","Modern Architecture","Design modern architecture"),
(868,"3D_MODELING","3D Modeling","Create a 3D model"),
(869,"RENDERING","Rendering","Render a design"),
(870,"ARCHITECTURE_ANALYSIS","Architecture Analysis","Analyze a building"),
(871,"CULINARY","Culinary Arts","Create a recipe"),
(872,"COOKING","Cooking","Cook a dish"),
(873,"BAKING","Baking","Bake a dessert"),
(874,"NUTRITION","Nutrition","Analyze nutrition"),
(875,"FOOD_STYLING","Food Styling","Style food"),
(876,"WINE","Wine","Pair wine with food"),
(877,"BEVERAGE","Beverage Design","Design a drink"),
(878,"FOOD_PHOTOGRAPHY","Food Photography","Photograph food"),
(879,"FOOD_BUSINESS","Food Business","Start a food business"),
(880,"CULINARY_HISTORY","Culinary History","Explain culinary history"),
(881,"ADVERTISING","Advertising","Create an ad campaign"),
(882,"CAMPAIGN","Campaign Strategy","Plan a campaign"),
(883,"DIRECT","Direct Marketing","Create a direct mail campaign"),
(884,"DIGITAL","Digital Marketing","Plan digital marketing"),
(885,"SOCIAL","Social Media Marketing","Plan social media"),
(886,"CONTENT_MARKET","Content Marketing","Create content marketing"),
(887,"INFLUENCER","Influencer Marketing","Plan influencer marketing"),
(888,"PR","Public Relations","Create a PR campaign"),
(889,"BRAND_STORY","Brand Storytelling","Tell a brand story"),
(890,"MARKETING_ANALYSIS","Marketing Analysis","Analyze marketing performance"),
(891,"GAME_DESIGN","Game Design","Design a game"),
(892,"GAME_DEV","Game Development","Develop a game"),
(893,"GAME_ANALYSIS","Game Analysis","Analyze a game"),
(894,"GAME_STRATEGY","Game Strategy","Create a game strategy"),
(895,"NARRATIVE","Narrative Design","Design a narrative"),
(896,"WORLD_BUILDING","World Building","Build a world"),
(897,"CHARACTER","Character Design","Design a character"),
(898,"LEVEL_DESIGN","Level Design","Design a game level"),
(899,"GAME_MUSIC","Game Music","Create game music"),
(900,"GAME_MARKETING","Game Marketing","Market a game"),
(901,"AI_FUTURE","Future of AI","What is the future of AI?"),
(902,"TECH_FUTURE","Future of Technology","What will technology look like in 2050?"),
(903,"SPACE_FUTURE","Future of Space","What is the future of space exploration?"),
(904,"ENERGY_FUTURE","Future of Energy","What will energy look like in 2050?"),
(905,"MEDICINE_FUTURE","Future of Medicine","What will medicine look like in 2050?"),
(906,"EDUCATION_FUTURE","Future of Education","What will education look like in 2050?"),
(907,"WORK_FUTURE","Future of Work","What will work look like in 2050?"),
(908,"CITIES_FUTURE","Future of Cities","What will cities look like in 2050?"),
(909,"TRANSPORT_FUTURE","Future of Transport","What will transport look like in 2050?"),
(910,"COMMUNICATION_FUTURE","Future of Communication","What will communication look like in 2050?"),
(911,"QUANTUM_FUTURE","Quantum Computing Future","What is the future of quantum computing?"),
(912,"BIO_FUTURE","Biotechnology Future","What is the future of biotech?"),
(913,"NANO_FUTURE","Nanotechnology Future","What is the future of nanotechnology?"),
(914,"ROBOTICS_FUTURE","Robotics Future","What is the future of robotics?"),
(915,"AI_SAFETY","AI Safety","How do we ensure AI safety?"),
(916,"AI_ETHICS","AI Ethics","What are the ethics of AI?"),
(917,"AI_GOVERNANCE","AI Governance","How should AI be governed?"),
(918,"AI_ALIGNMENT","AI Alignment","How do we align AI with human values?"),
(919,"AGI","Artificial General Intelligence","What is AGI and when will it arrive?"),
(920,"ASI","Artificial Superintelligence","What is ASI and what are its implications?"),
(921,"CLIMATE","Climate Change","What are the solutions to climate change?"),
(922,"SUSTAINABILITY","Sustainability","How do we achieve sustainability?"),
(923,"POVERTY","Poverty Alleviation","How do we end poverty?"),
(924,"HUNGER","Hunger","How do we end hunger?"),
(925,"DISEASE","Disease","How do we end disease?"),
(926,"WAR","Peace","How do we achieve world peace?"),
(927,"INEQUALITY","Inequality","How do we reduce inequality?"),
(928,"CORRUPTION","Corruption","How do we end corruption?"),
(929,"EDUCATION","Global Education","How do we educate everyone?"),
(930,"DEMOCRACY","Democracy","How do we strengthen democracy?"),
(931,"HUMAN_POTENTIAL","Human Potential","How do we unlock human potential?"),
(932,"CREATIVITY","Creativity","How do we foster creativity?"),
(933,"INNOVATION","Innovation","How do we drive innovation?"),
(934,"LEADERSHIP","Leadership","How do we develop leaders?"),
(935,"WELLNESS","Wellness","How do we achieve wellness?"),
(936,"HAPPINESS","Happiness","How do we achieve happiness?"),
(937,"RESILIENCE","Resilience","How do we build resilience?"),
(938,"MINDFULNESS","Mindfulness","How do we practice mindfulness?"),
(939,"PURPOSE","Purpose","How do we find purpose?"),
(940,"LEGACY","Legacy","How do we build a legacy?"),
(941,"COSMOS","Cosmos","What is the cosmos?"),
(942,"UNIVERSE","Universe","What is the universe?"),
(943,"MULTIVERSE","Multiverse","Does the multiverse exist?"),
(944,"CONSCIOUSNESS","Consciousness","What is consciousness?"),
(945,"EXISTENCE","Existence","Why do we exist?"),
(946,"MEANING","Meaning","What is the meaning of life?"),
(947,"SPIRITUALITY","Spirituality","What is spirituality?"),
(948,"MYSTICISM","Mysticism","What is mysticism?"),
(949,"MEDITATION","Meditation","How do I meditate?"),
(950,"TRANSCENDENCE","Transcendence","What is transcendence?"),
(951,"ART_HISTORY","Art History","Explain the history of art"),
(952,"CULTURAL_HISTORY","Cultural History","Explain cultural history"),
(953,"MUSIC_HISTORY","Music History","Explain the history of music"),
(954,"LITERARY_HISTORY","Literary History","Explain literary history"),
(955,"FILM_HISTORY","Film History","Explain the history of film"),
(956,"THEATER_HISTORY","Theater History","Explain the history of theater"),
(957,"DANCE_HISTORY","Dance History","Explain the history of dance"),
(958,"ARCHITECTURE_HISTORY","Architecture History","Explain the history of architecture"),
(959,"PHOTOGRAPHY_HISTORY","Photography History","Explain the history of photography"),
(960,"DESIGN_HISTORY","Design History","Explain the history of design"),
(961,"IDEAS","Ideas","Generate ideas"),
(962,"PHILOSOPHY","Philosophy","Explain philosophy"),
(963,"LOGIC","Logic","Apply logic"),
(964,"ETHICS","Ethics","Apply ethics"),
(965,"AESTHETICS","Aesthetics","Apply aesthetics"),
(966,"METAPHYSICS","Metaphysics","Explain metaphysics"),
(967,"EPISTEMOLOGY","Epistemology","Explain epistemology"),
(968,"ONTOLOGY","Ontology","Explain ontology"),
(969,"PHENOMENOLOGY","Phenomenology","Explain phenomenology"),
(970,"HERMENEUTICS","Hermeneutics","Apply hermeneutics"),
(971,"INVENTION","Invention","Invent something new"),
(972,"DISCOVERY","Discovery","Discover something new"),
(973,"EXPLORATION","Exploration","Explore the unknown"),
(974,"CURIOSITY","Curiosity","Ask a question"),
(975,"WONDER","Wonder","Be amazed"),
(976,"IMAGINATION","Imagination","Imagine something"),
(977,"DREAM","Dream","Interpret a dream"),
(978,"VISION","Vision","Create a vision"),
(979,"MISSION","Mission","Define a mission"),
(980,"PURPOSE","Purpose","Define a purpose"),
(981,"WISDOM","Wisdom","Share wisdom"),
(982,"KNOWLEDGE","Knowledge","Share knowledge"),
(983,"UNDERSTANDING","Understanding","Explain understanding"),
(984,"INSIGHT","Insight","Share insight"),
(985,"TRUTH","Truth","Seek truth"),
(986,"WISDOM_TEACH","Teaching Wisdom","Teach wisdom"),
(987,"KNOWLEDGE_SHARE","Sharing Knowledge","Share knowledge"),
(988,"UNDERSTANDING_DEEP","Deep Understanding","Deepen understanding"),
(989,"INSIGHT_DEEP","Deep Insight","Deepen insight"),
(990,"TRUTH_SEEK","Seeking Truth","Seek truth together"),
(991,"ULTIMATE","Ultimate Intelligence","What is ultimate intelligence?"),
(992,"INFINITE","Infinite Intelligence","What is infinite intelligence?"),
(993,"ETERNAL","Eternal Intelligence","What is eternal intelligence?"),
(994,"UNBOUNDED","Unbounded Intelligence","What is unbounded intelligence?"),
(995,"TRANSCENDENT","Transcendent Intelligence","What is transcendent intelligence?"),
(996,"DIVINE","Divine Intelligence","What is divine intelligence?"),
(997,"COSMIC","Cosmic Intelligence","What is cosmic intelligence?"),
(998,"UNIVERSAL","Universal Intelligence","What is universal intelligence?"),
(999,"ONE","Oneness","What is oneness?"),
(1000,"ALL","All Intelligence","What is all intelligence?"),
]
