# OraCool AI cores 601-800 (Clusters 7-8). (num, name, role, example)
PART3 = [
(601,"SALES_AGENT","Sales Automation","Automate our sales outreach"),
(602,"LEAD_AGENT","Lead Generation","Find and qualify leads"),
(603,"PROSPECT_AGENT","Prospecting","Prospect for new clients"),
(604,"OUTREACH_AGENT","Outreach Automation","Automate outreach emails"),
(605,"FOLLOWUP_AGENT","Follow-up Automation","Automate follow-ups"),
(606,"DEMO_AGENT","Demo Scheduling","Schedule product demos"),
(607,"QUOTE_AGENT","Quote Generation","Generate quotes"),
(608,"CONTRACT_AGENT","Contract Management","Manage contracts"),
(609,"CLOSE_AGENT","Closing Automation","Automate deal closing"),
(610,"SALES_REPORT","Sales Reporting","Generate sales reports"),
(611,"SUPPORT_AGENT","Customer Support","Respond to customer inquiries"),
(612,"TICKET_AGENT","Ticket Management","Manage support tickets"),
(613,"FAQ_AGENT","FAQ Automation","Answer FAQs"),
(614,"ONBOARDING_AGENT","Onboarding Automation","Onboard new customers"),
(615,"RETENTION_AGENT","Retention Automation","Reduce churn"),
(616,"FEEDBACK_AGENT","Feedback Collection","Collect customer feedback"),
(617,"CHAT_AGENT","Live Chat Support","Handle live chat"),
(618,"EMAIL_SUPPORT","Email Support","Handle email support"),
(619,"SOCIAL_SUPPORT","Social Media Support","Handle social media support"),
(620,"SUPPORT_REPORT","Support Reporting","Generate support reports"),
(621,"BLOG_AGENT","Blog Writing","Write blog posts"),
(622,"SOCIAL_AGENT","Social Media Content","Create social media content"),
(623,"VIDEO_AGENT","Video Scripting","Write video scripts"),
(624,"PODCAST_AGENT","Podcast Scripting","Write podcast scripts"),
(625,"EMAIL_AGENT","Email Campaigns","Create email campaigns"),
(626,"SEO_AGENT","SEO Content","Create SEO-optimized content"),
(627,"GRAPHIC_AGENT","Graphic Design","Design graphics"),
(628,"PRESENTATION_AGENT","Presentation Design","Design presentations"),
(629,"COPY_AGENT","Copywriting","Write copy"),
(630,"CONTENT_REPORT","Content Reporting","Report on content performance"),
(631,"DATA_AGENT","Data Entry","Enter data"),
(632,"EXTRACT_AGENT","Data Extraction","Extract data from documents"),
(633,"TRANSFORM_AGENT","Data Transformation","Transform data"),
(634,"LOAD_AGENT","Data Loading","Load data into systems"),
(635,"CLEAN_AGENT","Data Cleaning","Clean data"),
(636,"ANALYTICS_AGENT","Analytics","Analyze data"),
(637,"REPORTING_AGENT","Reporting","Generate reports"),
(638,"DASHBOARD_AGENT","Dashboard Creation","Create dashboards"),
(639,"INSIGHT_AGENT","Insight Generation","Generate insights"),
(640,"PREDICT_AGENT","Prediction","Make predictions"),
(641,"SCHEDULE_AGENT","Scheduling","Schedule meetings"),
(642,"CALENDAR_AGENT","Calendar Management","Manage calendars"),
(643,"EMAIL_MANAGE","Email Management","Organize emails"),
(644,"DOCUMENT_MANAGE","Document Management","Organize documents"),
(645,"TASK_MANAGE","Task Management","Manage tasks"),
(646,"PROJECT_MANAGE","Project Management","Manage projects"),
(647,"INVOICE_AGENT","Invoicing","Generate invoices"),
(648,"EXPENSE_AGENT","Expense Management","Track expenses"),
(649,"TRAVEL_AGENT","Travel Planning","Plan travel"),
(650,"ADMIN_REPORT","Administrative Reporting","Generate admin reports"),
(651,"RECRUIT_AGENT","Recruiting","Find candidates"),
(652,"SCREEN_AGENT","Screening","Screen candidates"),
(653,"INTERVIEW_AGENT","Interview Scheduling","Schedule interviews"),
(654,"ONBOARD_AGENT","Onboarding","Onboard new hires"),
(655,"TRAIN_AGENT","Training","Train employees"),
(656,"PERFORMANCE_AGENT","Performance Management","Manage performance"),
(657,"PAYROLL_AGENT","Payroll","Process payroll"),
(658,"BENEFITS_AGENT","Benefits Administration","Manage benefits"),
(659,"CULTURE_AGENT","Culture Building","Build company culture"),
(660,"HR_REPORT","HR Reporting","Generate HR reports"),
(661,"SEO_AGENT","SEO Automation","Optimize for search engines"),
(662,"PPC_AGENT","PPC Automation","Manage PPC campaigns"),
(663,"SOCIAL_MARKET","Social Media Marketing","Manage social media"),
(664,"EMAIL_MARKET","Email Marketing","Run email campaigns"),
(665,"CONTENT_MARKET","Content Marketing","Create content"),
(666,"BRAND_AGENT","Brand Management","Manage brand"),
(667,"INFLUENCER_AGENT","Influencer Marketing","Find influencers"),
(668,"EVENT_AGENT","Event Marketing","Plan events"),
(669,"LEAD_NURTURE","Lead Nurturing","Nurture leads"),
(670,"MARKET_REPORT","Marketing Reporting","Generate marketing reports"),
(671,"SUPPLY_CHAIN_AGENT","Supply Chain Management","Manage supply chain"),
(672,"INVENTORY_AGENT","Inventory Management","Manage inventory"),
(673,"LOGISTICS_AGENT","Logistics","Manage logistics"),
(674,"PROCUREMENT_AGENT","Procurement","Procure materials"),
(675,"WAREHOUSE_AGENT","Warehouse Management","Manage warehouse"),
(676,"QUALITY_AGENT","Quality Control","Ensure quality"),
(677,"PRODUCTION_AGENT","Production Planning","Plan production"),
(678,"DISTRIBUTION_AGENT","Distribution","Manage distribution"),
(679,"FULFILLMENT_AGENT","Fulfillment","Manage fulfillment"),
(680,"OPS_REPORT","Operations Reporting","Generate operations reports"),
(681,"CODE_AGENT","Code Generation","Write code"),
(682,"DEBUG_AGENT","Debugging","Debug code"),
(683,"TEST_AGENT","Testing","Write tests"),
(684,"DOCS_AGENT","Documentation","Write documentation"),
(685,"DEPLOY_AGENT","Deployment","Deploy code"),
(686,"DEV_OPS","DevOps Automation","Automate DevOps"),
(687,"CI_CD","CI/CD Automation","Automate CI/CD"),
(688,"MONITOR_AGENT","Monitoring","Monitor systems"),
(689,"SECURITY_AGENT","Security Automation","Automate security"),
(690,"DEV_REPORT","Development Reporting","Generate development reports"),
(691,"LEGAL_AGENT","Legal Automation","Automate legal tasks"),
(692,"FINANCE_AGENT","Finance Automation","Automate finance tasks"),
(693,"RISK_AGENT","Risk Management","Manage risk"),
(694,"COMPLIANCE_AGENT","Compliance Automation","Automate compliance"),
(695,"AUDIT_AGENT","Audit Automation","Automate audits"),
(696,"RESEARCH_AGENT","Research","Conduct research"),
(697,"INNOVATION_AGENT","Innovation","Drive innovation"),
(698,"STRATEGY_AGENT","Strategy","Develop strategy"),
(699,"VISION_AGENT","Vision","Set vision"),
(700,"SUMMA_AGENT","Ultimate Agent Orchestrator","Orchestrate all agents"),
(701,"VULCAN","DevOps & Infrastructure Automation","Deploy our app to production"),
(702,"JANUS","Database Management & Optimization","Optimize my database performance"),
(703,"ASTRA","Networking & Connectivity","Diagnose network issues in our office"),
(704,"BOREAS","Cloud Cost Optimization","Reduce our cloud spending by 20%"),
(705,"INVIDIA","GPU & AI Hardware Management","Allocate GPU resources for training"),
(706,"CARI","Mobile App Development","Build an Android app for our service"),
(707,"FUTURIA","Tech Trend Prediction","What will the next big tech trend be?"),
(708,"MAGNA","Big Data Analytics","Analyze this 100TB dataset"),
(709,"APEX","Enterprise Architecture Design","Design a scalable enterprise architecture"),
(710,"SUMMA","Ultimate AI Orchestrator","ORCHESTRATE ALL CORES"),
(711,"AWS","AWS Management","Deploy to AWS"),
(712,"AZURE","Azure Management","Deploy to Azure"),
(713,"GCP","GCP Management","Deploy to GCP"),
(714,"OCI","Oracle Cloud","Deploy to Oracle Cloud"),
(715,"DO","DigitalOcean","Deploy to DigitalOcean"),
(716,"LINODE","Linode","Deploy to Linode"),
(717,"VULTR","Vultr","Deploy to Vultr"),
(718,"HETZNER","Hetzner","Deploy to Hetzner"),
(719,"OVH","OVHcloud","Deploy to OVH"),
(720,"CLOUDFLARE","Cloudflare","Deploy to Cloudflare"),
(721,"POSTGRES","PostgreSQL Management","Manage PostgreSQL"),
(722,"MYSQL","MySQL Management","Manage MySQL"),
(723,"MONGODB","MongoDB Management","Manage MongoDB"),
(724,"REDIS","Redis Management","Manage Redis"),
(725,"ELASTIC","Elasticsearch","Manage Elasticsearch"),
(726,"CASSANDRA","Cassandra","Manage Cassandra"),
(727,"DYNAMODB","DynamoDB","Manage DynamoDB"),
(728,"FIREBASE","Firebase","Manage Firebase"),
(729,"SUPABASE","Supabase","Manage Supabase"),
(730,"COCKROACH","CockroachDB","Manage CockroachDB"),
(731,"DOCKER","Docker","Containerize this app"),
(732,"KUBERNETES","Kubernetes","Orchestrate with Kubernetes"),
(733,"TERRAFORM","Terraform","Infrastructure as code"),
(734,"ANSIBLE","Ansible","Automate with Ansible"),
(735,"CHEF","Chef","Automate with Chef"),
(736,"PUPPET","Puppet","Automate with Puppet"),
(737,"SALTSTACK","SaltStack","Automate with SaltStack"),
(738,"HELM","Helm","Manage Kubernetes with Helm"),
(739,"JENKINS","Jenkins","CI/CD with Jenkins"),
(740,"GITHUB_ACTIONS","GitHub Actions","CI/CD with GitHub Actions"),
(741,"PROMETHEUS","Prometheus","Monitor with Prometheus"),
(742,"GRAFANA","Grafana","Visualize with Grafana"),
(743,"ELK","ELK Stack","Log with ELK"),
(744,"DATADOG","Datadog","Monitor with Datadog"),
(745,"NEWRELIC","New Relic","Monitor with New Relic"),
(746,"SENTRY","Sentry","Error tracking with Sentry"),
(747,"LOGSTASH","Logstash","Log with Logstash"),
(748,"KIBANA","Kibana","Visualize with Kibana"),
(749,"ZABBIX","Zabbix","Monitor with Zabbix"),
(750,"NAGIOS","Nagios","Monitor with Nagios"),
(751,"JAVASCRIPT","JavaScript","Write JavaScript code"),
(752,"PYTHON","Python","Write Python code"),
(753,"JAVA","Java","Write Java code"),
(754,"C_SHARP","C#","Write C# code"),
(755,"C_PLUS","C++","Write C++ code"),
(756,"GO","Go","Write Go code"),
(757,"RUST","Rust","Write Rust code"),
(758,"PHP","PHP","Write PHP code"),
(759,"RUBY","Ruby","Write Ruby code"),
(760,"SWIFT","Swift","Write Swift code"),
(761,"REACT","React","Build with React"),
(762,"ANGULAR","Angular","Build with Angular"),
(763,"VUE","Vue","Build with Vue"),
(764,"NODE","Node.js","Build with Node.js"),
(765,"EXPRESS","Express","Build with Express"),
(766,"DJANGO","Django","Build with Django"),
(767,"FLASK","Flask","Build with Flask"),
(768,"SPRING","Spring","Build with Spring"),
(769,"NEXT","Next.js","Build with Next.js"),
(770,"NUXT","Nuxt","Build with Nuxt"),
(771,"NMAP","Nmap","Scan network with Nmap"),
(772,"WIRESHARK","Wireshark","Analyze traffic with Wireshark"),
(773,"METASPLOIT","Metasploit","Pen test with Metasploit"),
(774,"BURP","Burp Suite","Test with Burp Suite"),
(775,"OWASP","OWASP","Follow OWASP guidelines"),
(776,"NIKTO","Nikto","Scan with Nikto"),
(777,"SQLMAP","SQLMap","Test with SQLMap"),
(778,"ZAP","ZAP","Scan with ZAP"),
(779,"OSSEC","OSSEC","Monitor with OSSEC"),
(780,"SNORT","Snort","IDS with Snort"),
(781,"TENSORFLOW","TensorFlow","Build with TensorFlow"),
(782,"PYTORCH","PyTorch","Build with PyTorch"),
(783,"KERAS","Keras","Build with Keras"),
(784,"HUGGINGFACE","Hugging Face","Use Hugging Face models"),
(785,"OPENAI","OpenAI","Use OpenAI API"),
(786,"GROQ","Groq","Use Groq API"),
(787,"LLAMA","Llama","Use Llama model"),
(788,"MISTRAL","Mistral","Use Mistral model"),
(789,"GEMINI","Gemini","Use Gemini model"),
(790,"CLAUDE","Claude","Use Claude model"),
(791,"GIT","Git","Manage with Git"),
(792,"GITHUB","GitHub","Manage on GitHub"),
(793,"GITLAB","GitLab","Manage on GitLab"),
(794,"BITBUCKET","Bitbucket","Manage on Bitbucket"),
(795,"JIRA","Jira","Manage with Jira"),
(796,"TRELLO","Trello","Manage with Trello"),
(797,"ASANA","Asana","Manage with Asana"),
(798,"NOTION","Notion","Manage with Notion"),
(799,"SLACK","Slack","Manage with Slack"),
(800,"TEAMS","Teams","Manage with Teams"),
]
