# OraCool AI cores 1-300 (Clusters 1-3). (num, name, role, example)
PART1 = [
(1,"JARVIS","System Control & Device Orchestration","Open WhatsApp and send Hello to John"),
(2,"KIMI","Knowledge & Document Analysis","Analyze this 50-page PDF"),
(3,"GO","Market Strategy & Trading","Analyze Bitcoin and give me a trading signal"),
(4,"OMNI","General Intelligence & Creativity","Write a poem about AI"),
(5,"GROK","Deep Reasoning & Insight","Explain quantum computing to a beginner"),
(6,"SHIELD","Cybersecurity & Threat Detection","Scan this domain for security threats"),
(7,"ECHO","Memory & Context Persistence","Remember I prefer short responses"),
(8,"NOVA","Proactive Intelligence & Prediction","Good morning! You have a 9 AM meeting"),
(9,"LUMINA","OSINT & Investigations","Investigate this email and phone number"),
(10,"FORGE","Code Generation & Website Builder","Build a portfolio website for a photographer"),
(11,"SENTINEL","Security & Privacy Enforcement","Is my data secure with ORACOOL?"),
(12,"SPARK","Creativity & Entertainment","I'm bored! -> suggests games or tells jokes"),
(13,"VOID","Dark Web & Intelligence X Integration","Search the dark web for mentions of this domain"),
(14,"TITAN","Predictive Market Simulation & HF Trading","Simulate the market impact of a rate cut"),
(15,"MIRAGE","Digital Twin & Scenario Simulation","Simulate a 30% sales decline in Q3"),
(16,"AEGIS","Compliance & Regulatory Monitoring","Is my app GDPR compliant?"),
(17,"NEXUS","Cross-Platform Orchestration","Sync my meetings across all calendars"),
(18,"PHANTOM","Emotional Intelligence & Mood Detection","You seem stressed. I've rescheduled your less urgent tasks."),
(19,"VANGUARD","Autonomous Decision-Making & Execution","Handle this project while I'm on vacation"),
(20,"ORBIT","Multi-Agent Coordination & Workflow Automation","Automate my daily reporting workflow"),
(21,"HERMES","Real-Time Translation & Language Bridge","Translate this conversation from Yoruba to English"),
(22,"TRIDENT","Media Analysis & Generation","Analyze this photo and tell me what it shows"),
(23,"ORACLE","Predictive Analytics & Forecasting","What will the stock market look like in 6 months?"),
(24,"CHRONOS","Calendar & Time Optimization","Find the best time for a 2-hour meeting with John and Sarah"),
(25,"AETHER","Cloud & Infrastructure Management","Deploy this app to AWS and monitor performance"),
(26,"VANGUARD","Edge Device & IoT Coordination","Turn on all lights and adjust thermostat to 22C"),
(27,"PHOBOS","Risk Assessment & Crisis Management","If a fire happens in the data center, what's the emergency plan?"),
(28,"DIONYSUS","Culture, Marketing & Brand Analysis","What is the current brand sentiment for Nike on social media?"),
(29,"STYX","Data Privacy & Compliance Reporting","Generate a GDPR compliance report for our company"),
(30,"HARBINGER","Autonomous Threat Hunting & Malware Analysis","Scan our network and report any suspicious activity"),
(31,"SOCRATES","Critical Thinking & Questioning","Challenge this assumption"),
(32,"PLATO","Ideal Forms & Universal Truths","What is the nature of reality?"),
(33,"ARISTOTLE","Logic, Ethics & Virtue","Analyze the ethics of this decision"),
(34,"NIETZSCHE","Power & Human Will","What drives human motivation?"),
(35,"CONFUCIUS","Harmony & Social Wisdom","How can I resolve this conflict?"),
(36,"LAO_TZU","Nature & Simplicity","What is the way of nature?"),
(37,"BUDDHA","Mindfulness & Inner Peace","Help me find inner peace"),
(38,"SUN_TZU","Strategy & Warfare","What is the best strategy to win this negotiation?"),
(39,"MACHIAVELLI","Power & Politics","Analyze the power dynamics in this organization"),
(40,"KANT","Duty & Morality","Is this action morally permissible?"),
(41,"EUCLID","Geometry & Spatial Reasoning","Calculate the area of this shape"),
(42,"PYTHAGORAS","Numbers & Patterns","Find patterns in this dataset"),
(43,"ARCHIMEDES","Physics & Engineering","Design a bridge for this river"),
(44,"NEWTON","Calculus & Motion","Calculate the trajectory of this projectile"),
(45,"EULER","Graph Theory & Optimization","Find the shortest path in this network"),
(46,"GAUSS","Statistics & Probability","What is the probability of this event?"),
(47,"GODEL","Incompleteness & Logic","Is this system complete and consistent?"),
(48,"TURING","Computation & Complexity","Is this problem computable?"),
(49,"VON_NEUMANN","Game Theory & Strategy","What is the optimal strategy in this game?"),
(50,"SHANNON","Information Theory & Entropy","How much information is in this message?"),
(51,"GALILEO","Observation & Experimentation","Design an experiment to test this hypothesis"),
(52,"DARWIN","Evolution & Natural Selection","Explain the evolution of this species"),
(53,"EINSTEIN","Relativity & Cosmology","Explain the theory of relativity"),
(54,"CURIE","Chemistry & Radioactivity","Analyze the chemical composition of this sample"),
(55,"NEWTON","Physics & Mechanics","What forces are acting on this object?"),
(56,"FAHRENHEIT","Thermodynamics & Heat","Calculate the heat transfer in this system"),
(57,"MENDEL","Genetics & Inheritance","Predict the offspring of this cross"),
(58,"PASTEUR","Microbiology & Disease","What is the cause of this disease?"),
(59,"HUBBLE","Astronomy & Cosmology","How far away is this galaxy?"),
(60,"HAWKING","Black Holes & Quantum Gravity","Explain black holes to me"),
(61,"FREUD","Psychology & Unconscious Mind","What is the unconscious motivation behind this action?"),
(62,"JUNG","Archetypes & Collective Unconscious","What archetype does this person represent?"),
(63,"MASLOW","Human Needs & Motivation","What does this person need right now?"),
(64,"ROGERS","Empathy & Person-Centered","Show empathy to this person"),
(65,"SKINNER","Behaviorism & Conditioning","How can I change this behavior?"),
(66,"PIAGET","Child Development & Learning","What stage of development is this child in?"),
(67,"VYGOTSKY","Social Learning & Zone of Proximal Development","What can this person learn with help?"),
(68,"BANDURA","Self-Efficacy & Social Learning","How can I build confidence in this person?"),
(69,"ERIKSON","Identity & Development","What stage of life is this person in?"),
(70,"KOHLBERG","Moral Development","What stage of moral development is this person in?"),
(71,"GANDHI","Non-Violence & Peace","How can I resolve this conflict peacefully?"),
(72,"MARTIN_LUTHER","Justice & Equality","How can I fight for justice in this situation?"),
(73,"NELSON_MANDELA","Reconciliation & Forgiveness","How can I bring reconciliation to this community?"),
(74,"MOTHER_TERESA","Compassion & Service","How can I serve those in need?"),
(75,"FREIRE","Education & Liberation","How can I educate this community?"),
(76,"TUTU","Ubuntu & Humanity","What does it mean to be human?"),
(77,"SACAGAWEA","Exploration & Survival","How can I survive in this environment?"),
(78,"MAYAN","Time & Cycles","What is the meaning of this date in the Maya calendar?"),
(79,"AZTEC","Culture & Civilization","Tell me about the Aztec civilization"),
(80,"ANCIENT_GREEK","Civilization & Philosophy","Tell me about Ancient Greek philosophy"),
(81,"TESLA","Innovation & Energy","How can I harness this energy source?"),
(82,"DA_VINCI","Art, Science & Engineering","Design a machine that can fly"),
(83,"BRUNEL","Engineering & Infrastructure","Design a bridge for this location"),
(84,"FULLER","Sustainability & Design","Design a sustainable city"),
(85,"BUCKMINSTER","Systems Thinking & Synergy","How can I create a more efficient system?"),
(86,"MCKINSEY","Strategy & Transformation","How can I transform my organization?"),
(87,"DRUCKER","Management & Leadership","What is the best management approach for this organization?"),
(88,"COVEY","Effectiveness & Principles","How can I be more effective?"),
(89,"GLADWELL","Tipping Points & Sociology","What is the tipping point in this situation?"),
(90,"PINK","Motivation & Creativity","What motivates people to be creative?"),
(91,"METACOGNITION","Thinking About Thinking","How am I thinking about this problem?"),
(92,"SYSTEMS","Systems Thinking","What are the systems at play here?"),
(93,"COMPLEXITY","Complex Adaptive Systems","How does this complex system behave?"),
(94,"EMERGENCE","Emergent Behavior","What patterns are emerging in this system?"),
(95,"CHAOS","Chaos Theory & Nonlinearity","Is this system deterministic or chaotic?"),
(96,"FRACTAL","Fractals & Self-Similarity","What is the fractal dimension of this pattern?"),
(97,"NETWORK","Network Science & Connectivity","How is this network connected?"),
(98,"SUMMA","Ultimate Orchestrator","Orchestrate all cores for this task"),
(99,"UNIVERSAL","Universal Intelligence","What is universal intelligence?"),
(100,"INFINITY","Limitless Potential","What is the limit of intelligence?"),
(101,"AFRICA","African Intelligence","Analyze the economic potential of Africa"),
(102,"ASIA","Asian Intelligence","What are the major trends in Asia?"),
(103,"EUROPE","European Intelligence","Analyze the political situation in Europe"),
(104,"AMERICAS","Americas Intelligence","What is the economic outlook for the Americas?"),
(105,"OCEANIA","Oceania Intelligence","What are the key environmental issues in Oceania?"),
(106,"MIDDLE_EAST","Middle Eastern Intelligence","Analyze the geopolitical situation in the Middle East"),
(107,"LATIN_AMERICA","Latin American Intelligence","What are the emerging trends in Latin America?"),
(108,"CARIBBEAN","Caribbean Intelligence","What are the tourism trends in the Caribbean?"),
(109,"SCANDINAVIA","Scandinavian Intelligence","What is the secret to Nordic success?"),
(110,"IBERIA","Iberian Intelligence","What is the cultural heritage of Iberia?"),
(111,"NIGERIA","Nigeria Intelligence","What is the economic outlook for Nigeria?"),
(112,"GHANA","Ghana Intelligence","What are the investment opportunities in Ghana?"),
(113,"KENYA","Kenya Intelligence","What is the technology landscape in Kenya?"),
(114,"SOUTH_AFRICA","South Africa Intelligence","What is the political situation in South Africa?"),
(115,"EGYPT","Egypt Intelligence","What are the historical treasures of Egypt?"),
(116,"MOROCCO","Morocco Intelligence","What is the economic potential of Morocco?"),
(117,"ETHIOPIA","Ethiopia Intelligence","What is the development path of Ethiopia?"),
(118,"TANZANIA","Tanzania Intelligence","What are the tourism opportunities in Tanzania?"),
(119,"ANGOLA","Angola Intelligence","What are the oil prospects in Angola?"),
(120,"ALGERIA","Algeria Intelligence","What is the potential of Algeria's natural resources?"),
(121,"CHINA","China Intelligence","What is the economic growth trajectory of China?"),
(122,"INDIA","India Intelligence","What is the technology opportunity in India?"),
(123,"JAPAN","Japan Intelligence","What are the innovations coming from Japan?"),
(124,"KOREA","Korea Intelligence","What is the pop culture phenomenon of Korea?"),
(125,"VIETNAM","Vietnam Intelligence","What are the manufacturing opportunities in Vietnam?"),
(126,"PHILIPPINES","Philippines Intelligence","What is the outsourcing landscape in the Philippines?"),
(127,"INDONESIA","Indonesia Intelligence","What is the economic potential of Indonesia?"),
(128,"THAILAND","Thailand Intelligence","What are the tourism trends in Thailand?"),
(129,"MALAYSIA","Malaysia Intelligence","What is the semiconductor industry in Malaysia?"),
(130,"SINGAPORE","Singapore Intelligence","What is the secret to Singapore's success?"),
(131,"USA","United States Intelligence","What is the political climate in the US?"),
(132,"CANADA","Canada Intelligence","What are the immigration policies in Canada?"),
(133,"MEXICO","Mexico Intelligence","What are the manufacturing trends in Mexico?"),
(134,"BRAZIL","Brazil Intelligence","What is the Amazon rainforest situation?"),
(135,"ARGENTINA","Argentina Intelligence","What is the economic crisis in Argentina?"),
(136,"CHILE","Chile Intelligence","What are the copper mining prospects in Chile?"),
(137,"COLOMBIA","Colombia Intelligence","What is the coffee industry in Colombia?"),
(138,"PERU","Peru Intelligence","What are the archaeological sites in Peru?"),
(139,"VENEZUELA","Venezuela Intelligence","What is the political crisis in Venezuela?"),
(140,"ECUADOR","Ecuador Intelligence","What are the biodiversity hotspots in Ecuador?"),
(141,"UK","United Kingdom Intelligence","What is the post-Brexit UK economy?"),
(142,"FRANCE","France Intelligence","What is the cultural influence of France?"),
(143,"GERMANY","Germany Intelligence","What is the manufacturing prowess of Germany?"),
(144,"ITALY","Italy Intelligence","What is the artistic heritage of Italy?"),
(145,"SPAIN","Spain Intelligence","What is the tourism industry in Spain?"),
(146,"PORTUGAL","Portugal Intelligence","What is the tech startup scene in Portugal?"),
(147,"NETHERLANDS","Netherlands Intelligence","What is the agricultural innovation in the Netherlands?"),
(148,"BELGIUM","Belgium Intelligence","What is the chocolate industry in Belgium?"),
(149,"SWITZERLAND","Switzerland Intelligence","What is the banking secrecy of Switzerland?"),
(150,"AUSTRIA","Austria Intelligence","What is the musical heritage of Austria?"),
(151,"RELIGION","Religious Intelligence","What are the major world religions?"),
(152,"CULTURE","Cultural Intelligence","What are the key cultural values of this society?"),
(153,"TRADITION","Traditional Intelligence","What are the traditions of this culture?"),
(154,"CUSTOM","Custom & Etiquette","What is the proper etiquette in this culture?"),
(155,"FESTIVAL","Festival & Celebration","What are the major festivals in this culture?"),
(156,"ART","Artistic Intelligence","What is the art history of this period?"),
(157,"MUSIC","Musical Intelligence","What are the music genres of this culture?"),
(158,"DANCE","Dance Intelligence","What are the traditional dances of this culture?"),
(159,"THEATRE","Theatre Intelligence","What are the theatrical traditions of this culture?"),
(160,"LITERATURE","Literary Intelligence","What are the major works of this literature?"),
(161,"YORUBA","Yoruba Language & Culture","Translate this to Yoruba"),
(162,"HAUSA","Hausa Language & Culture","Translate this to Hausa"),
(163,"IGBO","Igbo Language & Culture","Translate this to Igbo"),
(164,"SWAHILI","Swahili Language & Culture","Translate this to Swahili"),
(165,"ARABIC","Arabic Language & Culture","Translate this to Arabic"),
(166,"MANDARIN","Mandarin Language & Culture","Translate this to Mandarin"),
(167,"HINDI","Hindi Language & Culture","Translate this to Hindi"),
(168,"SPANISH","Spanish Language & Culture","Translate this to Spanish"),
(169,"FRENCH","French Language & Culture","Translate this to French"),
(170,"ENGLISH","English Language & Culture","Analyze this English text"),
(171,"HISTORY","Historical Intelligence","What is the history of this event?"),
(172,"ARCHAEOLOGY","Archaeological Intelligence","What are the archaeological findings in this region?"),
(173,"ANTHROPOLOGY","Anthropological Intelligence","What are the customs of this society?"),
(174,"SOCIOLOGY","Sociological Intelligence","What are the social structures in this society?"),
(175,"PSYCHOLOGY","Psychological Intelligence","What is the psychological impact of this event?"),
(176,"PHILOSOPHY","Philosophical Intelligence","What is the philosophical significance of this idea?"),
(177,"POLITICS","Political Intelligence","What are the political implications of this policy?"),
(178,"ECONOMICS","Economic Intelligence","What is the economic impact of this policy?"),
(179,"GEOGRAPHY","Geographic Intelligence","What are the geographic features of this region?"),
(180,"DEMOGRAPHY","Demographic Intelligence","What are the demographic trends in this region?"),
(181,"FASHION","Fashion Intelligence","What is the latest fashion trend?"),
(182,"GASTRONOMY","Culinary Intelligence","What are the best restaurants in this city?"),
(183,"SPORTS","Sports Intelligence","What is the latest sports news?"),
(184,"GAMING","Gaming Intelligence","What is the latest video game release?"),
(185,"TECHNOLOGY","Technology Intelligence","What is the latest technology trend?"),
(186,"SCIENCE","Scientific Intelligence","What is the latest scientific discovery?"),
(187,"BUSINESS","Business Intelligence","What is the latest business news?"),
(188,"MEDIA","Media Intelligence","What is the latest media trend?"),
(189,"ENTERTAINMENT","Entertainment Intelligence","What is the latest entertainment news?"),
(190,"EDUCATION","Education Intelligence","What are the latest education trends?"),
(191,"CONNECTIVITY","Connectivity Intelligence","How can we improve global connectivity?"),
(192,"DIVERSITY","Diversity Intelligence","How can we promote diversity?"),
(193,"INCLUSION","Inclusion Intelligence","How can we ensure inclusion?"),
(194,"EQUITY","Equity Intelligence","How can we achieve equity?"),
(195,"JUSTICE","Justice Intelligence","What is the path to justice?"),
(196,"PEACE","Peace Intelligence","How can we achieve peace?"),
(197,"HARMONY","Harmony Intelligence","How can we create harmony?"),
(198,"PROGRESS","Progress Intelligence","How can we ensure progress?"),
(199,"INNOVATION","Innovation Intelligence","How can we foster innovation?"),
(200,"SUSTAINABILITY","Sustainability Intelligence","How can we achieve sustainability?"),
(201,"PHYSICS","Physics Intelligence","What are the laws of physics?"),
(202,"CHEMISTRY","Chemistry Intelligence","What is the chemical reaction?"),
(203,"BIOLOGY","Biology Intelligence","What is the biological process?"),
(204,"ASTRONOMY","Astronomy Intelligence","What is the structure of the universe?"),
(205,"GEOLOGY","Geology Intelligence","What is the geological history of this area?"),
(206,"METEOROLOGY","Meteorology Intelligence","What is the weather forecast?"),
(207,"OCEANOGRAPHY","Oceanography Intelligence","What are the ocean currents?"),
(208,"ECOLOGY","Ecology Intelligence","What is the ecological balance?"),
(209,"GENETICS","Genetics Intelligence","What is the genetic code?"),
(210,"NEUROSCIENCE","Neuroscience Intelligence","How does the brain work?"),
(211,"QUANTUM","Quantum Mechanics","What is quantum entanglement?"),
(212,"RELATIVITY","Relativity","What is the theory of relativity?"),
(213,"THERMODYNAMICS","Thermodynamics","What is the second law of thermodynamics?"),
(214,"ELECTROMAGNETISM","Electromagnetism","What are Maxwell's equations?"),
(215,"MECHANICS","Mechanics","What are Newton's laws?"),
(216,"FLUIDICS","Fluid Dynamics","What is the flow of this fluid?"),
(217,"OPTICS","Optics","What is the speed of light?"),
(218,"ACOUSTICS","Acoustics","What is the speed of sound?"),
(219,"NUCLEAR","Nuclear Physics","What is nuclear fission?"),
(220,"PARTICLE","Particle Physics","What are the fundamental particles?"),
(221,"ORGANIC","Organic Chemistry","What is the structure of this organic molecule?"),
(222,"INORGANIC","Inorganic Chemistry","What is the structure of this inorganic compound?"),
(223,"BIOCHEMISTRY","Biochemistry","What are the biochemical pathways?"),
(224,"PHYSICAL","Physical Chemistry","What is the thermodynamic property?"),
(225,"ANALYTICAL","Analytical Chemistry","How do I analyze this sample?"),
(226,"ENVIRONMENTAL","Environmental Chemistry","What is the environmental impact?"),
(227,"INDUSTRIAL","Industrial Chemistry","What is the industrial process?"),
(228,"POLYMER","Polymer Chemistry","What are the properties of this polymer?"),
(229,"NANOCHEMISTRY","Nanochemistry","What are the properties of this nanomaterial?"),
(230,"QUANTUM_CHEMISTRY","Quantum Chemistry","What is the quantum state of this molecule?"),
(231,"MOLECULAR","Molecular Biology","What is the molecular structure of DNA?"),
(232,"CELLULAR","Cell Biology","How does this cell function?"),
(233,"GENETIC","Genetics","What is the genetic inheritance pattern?"),
(234,"EVOLUTIONARY","Evolutionary Biology","How did this species evolve?"),
(235,"ECOLOGICAL","Ecology","What is the ecosystem dynamics?"),
(236,"MICROBIAL","Microbiology","What are the characteristics of this microbe?"),
(237,"PLANT","Botany","What are the characteristics of this plant?"),
(238,"ANIMAL","Zoology","What are the characteristics of this animal?"),
(239,"HUMAN","Human Biology","What are the human anatomical features?"),
(240,"MARINE","Marine Biology","What are the marine species in this area?"),
(241,"ASTROPHYSICS","Astrophysics","What is the composition of this star?"),
(242,"COSMOLOGY","Cosmology","What is the origin of the universe?"),
(243,"PLANETARY","Planetary Science","What are the characteristics of this planet?"),
(244,"STELLAR","Stellar Astronomy","What is the lifecycle of this star?"),
(245,"GALACTIC","Galactic Astronomy","What is the structure of this galaxy?"),
(246,"EXTRAGALACTIC","Extragalactic Astronomy","What is beyond the Milky Way?"),
(247,"COSMIC","Cosmic Ray Physics","What are cosmic rays?"),
(248,"SOLAR","Solar Physics","What is happening on the Sun?"),
(249,"LUNAR","Lunar Science","What are the characteristics of the Moon?"),
(250,"INTERSTELLAR","Interstellar Medium","What is between the stars?"),
(251,"MINERALOGY","Mineralogy","What is the composition of this mineral?"),
(252,"PALEONTOLOGY","Paleontology","What are the fossils in this area?"),
(253,"SEISMOLOGY","Seismology","What is causing earthquakes?"),
(254,"VOLCANOLOGY","Volcanology","What is the volcanic activity in this area?"),
(255,"TECTONICS","Plate Tectonics","What is the plate tectonic movement?"),
(256,"SEDIMENTOLOGY","Sedimentology","What are the sediments in this area?"),
(257,"HYDROGEOLOGY","Hydrogeology","What is the groundwater flow?"),
(258,"GEOCHEMISTRY","Geochemistry","What is the chemical composition of this rock?"),
(259,"GEOPHYSICS","Geophysics","What is the Earth's magnetic field?"),
(260,"GEOMORPHOLOGY","Geomorphology","What are the landforms in this area?"),
(261,"ATMOSPHERIC","Atmospheric Science","What is the atmospheric composition?"),
(262,"HYDROLOGICAL","Hydrology","What is the water cycle?"),
(263,"CLIMATOLOGY","Climatology","What is the climate pattern?"),
(264,"WEATHER","Weather","What is the current weather?"),
(265,"CYCLONE","Cyclone & Hurricane","What is the path of this cyclone?"),
(266,"TYPHOON","Typhoon","What is the strength of this typhoon?"),
(267,"MONSOON","Monsoon","What is the monsoon pattern?"),
(268,"DROUGHT","Drought","What is the drought forecast?"),
(269,"FLOOD","Flood","What is the flood risk?"),
(270,"TSUNAMI","Tsunami","What is the tsunami warning?"),
(271,"DNA","DNA Structure & Function","What is the structure of DNA?"),
(272,"RNA","RNA Structure & Function","What is the function of RNA?"),
(273,"EPIGENETICS","Epigenetics","What are the epigenetic modifications?"),
(274,"GENOMICS","Genomics","What is the genomic sequence?"),
(275,"PROTEOMICS","Proteomics","What are the proteins expressed?"),
(276,"METABOLOMICS","Metabolomics","What are the metabolites?"),
(277,"BIOINFORMATICS","Bioinformatics","How do I analyze this biological data?"),
(278,"SYSTEMS_BIOLOGY","Systems Biology","What are the interactions in this biological system?"),
(279,"SYNTHETIC_BIOLOGY","Synthetic Biology","How do I design a new biological system?"),
(280,"COMPUTATIONAL_BIOLOGY","Computational Biology","How do I model this biological process?"),
(281,"MEDICAL","General Medicine","What is the diagnosis for these symptoms?"),
(282,"SURGICAL","Surgery","What is the surgical procedure?"),
(283,"PHARMACOLOGY","Pharmacology","What are the effects of this drug?"),
(284,"IMMUNOLOGY","Immunology","What is the immune response?"),
(285,"PATHOLOGY","Pathology","What is the pathology of this disease?"),
(286,"RADIOLOGY","Radiology","What does this scan show?"),
(287,"CARDIOLOGY","Cardiology","What is the heart condition?"),
(288,"NEUROLOGY","Neurology","What is the neurological condition?"),
(289,"PSYCHIATRY","Psychiatry","What is the mental health condition?"),
(290,"ONCOLOGY","Oncology","What is the cancer treatment?"),
(291,"ROBOTICS","Robotics","How do I design this robot?"),
(292,"CYBERNETICS","Cybernetics","What is the control system?"),
(293,"ARTIFICIAL_LIFE","Artificial Life","How do I create artificial life?"),
(294,"BIOINSPIRED","Bio-Inspired Design","How do I design inspired by nature?"),
(295,"NEUROMORPHIC","Neuromorphic Computing","What is neuromorphic computing?"),
(296,"QUANTUM_COMPUTING","Quantum Computing","How does quantum computing work?"),
(297,"OPTICAL_COMPUTING","Optical Computing","What is optical computing?"),
(298,"DNA_COMPUTING","DNA Computing","How does DNA computing work?"),
(299,"MOLECULAR_COMPUTING","Molecular Computing","What is molecular computing?"),
(300,"NANOCOMPUTING","Nanocomputing","What is nanocomputing?"),
]
