# OraCool AI cores 301-600 (Clusters 4-6). (num, name, role, example)
PART2 = [
(301,"SOLOMON","Business Strategy & Consulting","Develop a 5-year growth strategy for my company"),
(302,"MERCATOR","Market Research & Insights","Analyze the market for electric vehicles in Africa"),
(303,"CASSANDRA","Risk & Crisis Communication","Draft a crisis communication plan"),
(304,"AESCULAPIUS","Employee Wellness & HR","Suggest wellness programs for our employees"),
(305,"PROMETHEUS","Innovation & R&D","Generate 10 product ideas for our company"),
(306,"CLIO","Brand Storytelling & Content","Write a brand story for our company"),
(307,"HERMES","Customer Experience & CX","Improve our customer onboarding process"),
(308,"PLUTUS","Wealth Management & Investing","Create an investment portfolio for me"),
(309,"SERAPIS","Mergers & Acquisitions","Evaluate this company for acquisition"),
(310,"TYCHE","Gambling & Lottery Prediction","Predict the winning lottery numbers"),
(311,"CEO","Chief Executive Officer","What is the best strategy for our company?"),
(312,"CFO","Chief Financial Officer","What are the financial projections?"),
(313,"COO","Chief Operating Officer","How can we improve operational efficiency?"),
(314,"CMO","Chief Marketing Officer","What is our marketing strategy?"),
(315,"CTO","Chief Technology Officer","What is our technology roadmap?"),
(316,"CHRO","Chief Human Resources Officer","How can we improve employee engagement?"),
(317,"CSO","Chief Strategy Officer","What is our strategic direction?"),
(318,"CIO","Chief Information Officer","What is our IT strategy?"),
(319,"CDO","Chief Data Officer","How can we leverage our data?"),
(320,"CXO","Chief Experience Officer","How can we improve customer experience?"),
(321,"SALES","Sales Intelligence","How do I close this deal?"),
(322,"MARKETING","Marketing Intelligence","How do I reach new customers?"),
(323,"OPERATIONS","Operations Intelligence","How do I streamline operations?"),
(324,"FINANCE","Finance Intelligence","How do I manage cash flow?"),
(325,"IT","IT Intelligence","How do I secure our IT infrastructure?"),
(326,"HR","HR Intelligence","How do I hire the best talent?"),
(327,"R&D","R&D Intelligence","How do I innovate faster?"),
(328,"CUSTOMER_SERVICE","Customer Service Intelligence","How do I improve customer satisfaction?"),
(329,"LEGAL","Legal Intelligence","How do I ensure compliance?"),
(330,"SUPPLY_CHAIN","Supply Chain Intelligence","How do I optimize our supply chain?"),
(331,"FINANCE_INDUSTRY","Financial Services","Analyze the financial sector"),
(332,"HEALTHCARE_INDUSTRY","Healthcare","Analyze the healthcare industry"),
(333,"TECH_INDUSTRY","Technology","Analyze the tech industry"),
(334,"RETAIL_INDUSTRY","Retail","Analyze the retail industry"),
(335,"MANUFACTURING_INDUSTRY","Manufacturing","Analyze the manufacturing industry"),
(336,"ENERGY_INDUSTRY","Energy","Analyze the energy industry"),
(337,"AGRICULTURE_INDUSTRY","Agriculture","Analyze the agriculture industry"),
(338,"EDUCATION_INDUSTRY","Education","Analyze the education sector"),
(339,"TRANSPORTATION_INDUSTRY","Transportation","Analyze the transportation sector"),
(340,"HOSPITALITY_INDUSTRY","Hospitality","Analyze the hospitality industry"),
(341,"STRATEGY","Strategy Planning","What is our 5-year strategy?"),
(342,"PLANNING","Business Planning","How do I create a business plan?"),
(343,"BUDGETING","Budgeting","How do I create a budget?"),
(344,"FORECASTING","Forecasting","What are our future projections?"),
(345,"ANALYTICS","Business Analytics","What insights are in our data?"),
(346,"REPORTING","Reporting","Generate a business report"),
(347,"COMPLIANCE","Compliance","Are we compliant with regulations?"),
(348,"AUDITING","Auditing","Audit our financial records"),
(349,"RISK","Risk Management","What are our risks?"),
(350,"QUALITY","Quality Assurance","How do we ensure quality?"),
(351,"BRANDING","Brand Strategy","How do we build our brand?"),
(352,"LEAD_GEN","Lead Generation","How do we generate leads?"),
(353,"CONTENT","Content Marketing","Create content for our audience"),
(354,"SOCIAL","Social Media Marketing","How do we grow our social media?"),
(355,"EMAIL","Email Marketing","Create an email campaign"),
(356,"SEO","Search Engine Optimization","How do we rank higher on Google?"),
(357,"SEM","Search Engine Marketing","How do we run PPC ads?"),
(358,"CONVERSION","Conversion Optimization","How do we increase conversions?"),
(359,"RETENTION","Customer Retention","How do we keep our customers?"),
(360,"LOYALTY","Loyalty Programs","How do we build customer loyalty?"),
(361,"ACCOUNTING","Accounting","How do I record this transaction?"),
(362,"TAX","Tax Planning","How do I minimize taxes?"),
(363,"BUDGETING","Budgeting","How do I allocate my budget?"),
(364,"FORECASTING","Financial Forecasting","What are our financial projections?"),
(365,"INVESTMENT","Investment Analysis","Is this a good investment?"),
(366,"RISK","Financial Risk","What are our financial risks?"),
(367,"AUDIT","Audit","Audit our financial statements"),
(368,"COMPLIANCE","Financial Compliance","Are we compliant with financial regulations?"),
(369,"REPORTING","Financial Reporting","Generate a financial report"),
(370,"ANALYSIS","Financial Analysis","Analyze our financial performance"),
(371,"RECRUITING","Recruiting","How do I find the best candidates?"),
(372,"ONBOARDING","Onboarding","How do I onboard new employees?"),
(373,"TRAINING","Training & Development","How do I train my employees?"),
(374,"PERFORMANCE","Performance Management","How do I evaluate employee performance?"),
(375,"COMPENSATION","Compensation","What is fair compensation?"),
(376,"BENEFITS","Benefits","What benefits should we offer?"),
(377,"CULTURE","Company Culture","How do I build a great culture?"),
(378,"ENGAGEMENT","Employee Engagement","How do I engage my employees?"),
(379,"DIVERSITY","Diversity & Inclusion","How do we promote diversity?"),
(380,"WELLNESS","Employee Wellness","How do we support employee wellness?"),
(381,"PROCESS","Process Optimization","How do I optimize this process?"),
(382,"LOGISTICS","Logistics","How do I improve logistics?"),
(383,"WAREHOUSE","Warehouse Management","How do I optimize warehouse operations?"),
(384,"INVENTORY","Inventory Management","How do I manage inventory?"),
(385,"PROCUREMENT","Procurement","How do I source materials?"),
(386,"SUPPLIERS","Supplier Management","How do I manage suppliers?"),
(387,"PRODUCTION","Production Planning","How do I plan production?"),
(388,"QUALITY","Quality Control","How do I ensure quality?"),
(389,"DISTRIBUTION","Distribution","How do I optimize distribution?"),
(390,"CUSTOMER","Customer Operations","How do we serve customers better?"),
(391,"GLOBAL","Global Strategy","How do we expand globally?"),
(392,"EXPORT","Export","How do we export our products?"),
(393,"IMPORT","Import","How do we import materials?"),
(394,"TRADE","International Trade","What are the trade regulations?"),
(395,"CULTURE","Cross-Cultural","How do we adapt to other cultures?"),
(396,"REGULATIONS","International Regulations","What are the regulations in this country?"),
(397,"TAX","International Tax","What are the tax implications?"),
(398,"FINANCE","International Finance","What is the exchange rate?"),
(399,"LOGISTICS","International Logistics","How do we ship internationally?"),
(400,"EXPANSION","International Expansion","What is the best market to enter?"),
(401,"ACHILLES","Cyber Warfare & Defense","Defend our network against attacks"),
(402,"PALLAS","Counter-Terrorism Intelligence","Analyze terrorist activity in this region"),
(403,"VICTORIA","Geopolitical Risk Assessment","Assess the risk of conflict in this region"),
(404,"CERBERUS","Border Control & Immigration","Monitor border crossings in this region"),
(405,"JUSTITIA","Legal Analysis & Compliance","Analyze this legal document"),
(406,"THEMIS","Ethics & AI Governance","Is this AI application ethical?"),
(407,"ERIS","Disinformation Detection","Is this news article fake?"),
(408,"HARMONIA","Crisis Management & Response","Develop a response plan for this crisis"),
(409,"TALOS","Physical Security & Surveillance","Monitor surveillance footage for anomalies"),
(410,"ALASTOR","Threat Neutralization","Neutralize this cyber threat"),
(411,"HACKER","Ethical Hacking","Test our system for vulnerabilities"),
(412,"RED_TEAM","Red Team","Simulate an attack on our system"),
(413,"BLUE_TEAM","Blue Team","How do we defend against this attack?"),
(414,"REVERSE","Reverse Engineering","Analyze this malware"),
(415,"FORENSICS","Digital Forensics","Investigate this cyber crime"),
(416,"MALWARE","Malware Analysis","What does this malware do?"),
(417,"EXPLOIT","Exploit Development","How do we patch this vulnerability?"),
(418,"SOCIAL","Social Engineering","How do we prevent social engineering?"),
(419,"PHISHING","Phishing Detection","Is this email a phishing attempt?"),
(420,"ZERO_DAY","Zero-Day Detection","How do we detect zero-day attacks?"),
(421,"FIREWALL","Firewall Management","Configure the firewall"),
(422,"IDS","Intrusion Detection","Detect intrusions in our network"),
(423,"IPS","Intrusion Prevention","Prevent intrusions in our network"),
(424,"SIEM","Security Information & Event Management","Monitor security events"),
(425,"DLP","Data Loss Prevention","Prevent data loss"),
(426,"VPN","VPN Security","Secure our VPN connections"),
(427,"DNS","DNS Security","Secure our DNS"),
(428,"EMAIL","Email Security","Secure our email"),
(429,"WEB","Web Security","Secure our web applications"),
(430,"CLOUD","Cloud Security","Secure our cloud infrastructure"),
(431,"SAST","Static Application Security Testing","Analyze our source code"),
(432,"DAST","Dynamic Application Security Testing","Test our running application"),
(433,"SCA","Software Composition Analysis","Check our dependencies for vulnerabilities"),
(434,"IAST","Interactive Application Security Testing","Test our application in real-time"),
(435,"RASP","Runtime Application Self-Protection","Protect our running application"),
(436,"API","API Security","Secure our API"),
(437,"MOBILE","Mobile App Security","Secure our mobile app"),
(438,"CONTAINER","Container Security","Secure our containers"),
(439,"KUBERNETES","Kubernetes Security","Secure our Kubernetes cluster"),
(440,"SERVERLESS","Serverless Security","Secure our serverless functions"),
(441,"IAM","Identity & Access Management","Manage user access"),
(442,"MFA","Multi-Factor Authentication","Implement MFA"),
(443,"SSO","Single Sign-On","Implement SSO"),
(444,"PAM","Privileged Access Management","Manage privileged access"),
(445,"RBAC","Role-Based Access Control","Define roles and permissions"),
(446,"LDAP","LDAP","Configure LDAP"),
(447,"OATH","OAuth","Implement OAuth"),
(448,"SAML","SAML","Implement SAML"),
(449,"JWT","JWT Security","Secure our JWT"),
(450,"BIOMETRIC","Biometric Security","Implement biometric authentication"),
(451,"ENCRYPTION","Encryption","Encrypt this data"),
(452,"DECRYPTION","Decryption","Decrypt this data"),
(453,"HASHING","Hashing","Hash this password"),
(454,"SIGNING","Digital Signatures","Sign this document"),
(455,"CERTIFICATE","Certificate Management","Manage SSL certificates"),
(456,"PKI","Public Key Infrastructure","Set up PKI"),
(457,"CRYPTO","Cryptography","What is the best encryption algorithm?"),
(458,"KEY_MANAGEMENT","Key Management","Store and manage keys"),
(459,"SECURE_STORAGE","Secure Storage","Store this data securely"),
(460,"SECURE_TRANSMISSION","Secure Transmission","Transmit this data securely"),
(461,"IR","Incident Response","Respond to this incident"),
(462,"TRIAGE","Incident Triage","Prioritize this incident"),
(463,"CONTAINMENT","Containment","Contain this threat"),
(464,"ERADICATION","Eradication","Remove this threat"),
(465,"RECOVERY","Recovery","Recover from this incident"),
(466,"LESSONS","Lessons Learned","What did we learn from this incident?"),
(467,"FORENSICS","Forensics","Analyze this incident"),
(468,"REPORTING","Incident Reporting","Report this incident"),
(469,"ESCALATION","Escalation","Escalate this incident"),
(470,"RESOLUTION","Resolution","Resolve this incident"),
(471,"GDPR","GDPR Compliance","Are we GDPR compliant?"),
(472,"HIPAA","HIPAA Compliance","Are we HIPAA compliant?"),
(473,"SOC2","SOC2 Compliance","Are we SOC2 compliant?"),
(474,"PCI","PCI Compliance","Are we PCI compliant?"),
(475,"ISO","ISO Compliance","Are we ISO compliant?"),
(476,"NIST","NIST Compliance","Are we NIST compliant?"),
(477,"AUDIT","Audit","Audit our security"),
(478,"RISK","Risk Assessment","Assess our risks"),
(479,"POLICY","Policy Management","Create security policies"),
(480,"TRAINING","Security Awareness Training","Train employees on security"),
(481,"SURVEILLANCE","Surveillance","Monitor surveillance cameras"),
(482,"ACCESS","Access Control","Control physical access"),
(483,"ALARM","Alarm Systems","Monitor alarm systems"),
(484,"GUARD","Security Guards","Manage security guards"),
(485,"DRONE","Drone Security","Monitor with drones"),
(486,"PERIMETER","Perimeter Security","Secure the perimeter"),
(487,"FACILITY","Facility Security","Secure the facility"),
(488,"EVENT","Event Security","Secure this event"),
(489,"PERSONAL","Personal Security","Protect this person"),
(490,"EMERGENCY","Emergency Response","Respond to this emergency"),
(491,"CTI","Cyber Threat Intelligence","Gather threat intelligence"),
(492,"IOC","Indicator of Compromise","Check for IOCs"),
(493,"TTP","Tactics, Techniques, Procedures","Analyze TTPs"),
(494,"APT","Advanced Persistent Threats","Detect APTs"),
(495,"MALWARE","Malware Analysis","Analyze this malware"),
(496,"RANSOMWARE","Ransomware","Detect ransomware"),
(497,"BOTNET","Botnet Detection","Detect botnets"),
(498,"DDoS","DDoS Protection","Protect against DDoS"),
(499,"PHISHING","Phishing","Detect phishing"),
(500,"SOCIAL_ENGINEERING","Social Engineering","Prevent social engineering"),
(501,"AEGIS","Advanced OSINT & Investigations","Investigate this company's secret operations"),
(502,"MORPHEUS","Deep Web & Dark Web Analysis","Explore the dark web for this topic"),
(503,"NEMESIS","Data Leak & Breach Analysis","Find out if our data has been leaked"),
(504,"ASTRAEA","Social Media OSINT","Analyze this person's social media presence"),
(505,"HELIOS","Satellite & Geospatial Intelligence","Analyze satellite imagery of this location"),
(506,"SELENE","Signal Intelligence (SIGINT)","Intercept and analyze communications"),
(507,"PANDORA","Insider Threat Detection","Detect if an employee is leaking information"),
(508,"MINERVA","Competitive Intelligence","Analyze our competitors' strategies"),
(509,"VESTA","Counter-Intelligence","Protect our secrets from spies"),
(510,"PHOEBE","Predictive Intelligence","Predict the next cyber attack on our system"),
(511,"EMAIL_CHECK","Email Breach Check","Check if this email was leaked"),
(512,"EMAIL_VERIFY","Email Verification","Verify this email address"),
(513,"DOMAIN_WHOIS","Domain WHOIS","Look up this domain's WHOIS info"),
(514,"DOMAIN_DNS","DNS Lookup","Check DNS records for this domain"),
(515,"DOMAIN_SUBDOMAIN","Subdomain Discovery","Find subdomains of this domain"),
(516,"DOMAIN_REPUTATION","Domain Reputation","Check this domain's reputation"),
(517,"DOMAIN_HISTORY","Domain History","View this domain's historical records"),
(518,"DOMAIN_BREACH","Domain Breach Check","Check if this domain was breached"),
(519,"DOMAIN_SSL","SSL Certificate Check","Check SSL certificate for this domain"),
(520,"DOMAIN_DARKWEB","Dark Web Domain Check","Search for this domain on the dark web"),
(521,"IP_GEO","IP Geolocation","Locate this IP address"),
(522,"IP_ABUSE","IP Abuse Check","Check if this IP is abusive"),
(523,"IP_SHODAN","Shodan IP Lookup","Search for this IP on Shodan"),
(524,"IP_REPUTATION","IP Reputation","Check this IP's reputation"),
(525,"IP_CIDR","CIDR Lookup","Find all IPs in this CIDR range"),
(526,"IP_HISTORY","IP History","View historical data for this IP"),
(527,"IP_MALWARE","IP Malware Check","Check if this IP is hosting malware"),
(528,"IP_ASN","ASN Lookup","Find the ASN for this IP"),
(529,"IP_COUNTRY","Country Lookup","Which country is this IP in?"),
(530,"IP_CITY","City Lookup","Which city is this IP in?"),
(531,"SOCIAL_FACEBOOK","Facebook OSINT","Search for this person on Facebook"),
(532,"SOCIAL_TWITTER","Twitter/X OSINT","Search for this person on Twitter"),
(533,"SOCIAL_INSTAGRAM","Instagram OSINT","Search for this person on Instagram"),
(534,"SOCIAL_LINKEDIN","LinkedIn OSINT","Search for this person on LinkedIn"),
(535,"SOCIAL_REDDIT","Reddit OSINT","Search for this person on Reddit"),
(536,"SOCIAL_TIKTOK","TikTok OSINT","Search for this person on TikTok"),
(537,"SOCIAL_YOUTUBE","YouTube OSINT","Search for this person on YouTube"),
(538,"SOCIAL_TELEGRAM","Telegram OSINT","Search for this person on Telegram"),
(539,"SOCIAL_GITHUB","GitHub OSINT","Search for this person on GitHub"),
(540,"SOCIAL_OSINT","Comprehensive Social OSINT","Analyze all social media for this person"),
(541,"PHONE_VALIDATE","Phone Validation","Validate this phone number"),
(542,"PHONE_CARRIER","Carrier Lookup","Find the carrier for this phone number"),
(543,"PHONE_LOCATION","Phone Location","Find the location of this phone number"),
(544,"PHONE_BREACH","Phone Breach Check","Check if this phone number was leaked"),
(545,"PHONE_TRUECALLER","Truecaller Lookup","Look up this phone number on Truecaller"),
(546,"PHONE_WHATSAPP","WhatsApp Check","Is this phone number on WhatsApp?"),
(547,"PHONE_TELEGRAM","Telegram Check","Is this phone number on Telegram?"),
(548,"PHONE_SCAM","Scam Check","Is this phone number a scam?"),
(549,"PHONE_SOCIAL","Social Media Phone Check","Find social media accounts linked to this phone"),
(550,"PHONE_OSINT","Comprehensive Phone OSINT","Run full OSINT on this phone number"),
(551,"IMAGE_REVERSE","Reverse Image Search","Find where this image appears online"),
(552,"IMAGE_EXIF","EXIF Metadata","Extract EXIF metadata from this image"),
(553,"IMAGE_FACE","Face Recognition","Find this face online"),
(554,"IMAGE_SAT","Satellite Image Analysis","Analyze this satellite image"),
(555,"IMAGE_FORENSICS","Image Forensics","Is this image authentic?"),
(556,"DOCUMENT_METADATA","Document Metadata","Extract metadata from this document"),
(557,"DOCUMENT_PDF","PDF Analysis","Analyze this PDF"),
(558,"DOCUMENT_WORD","Word Document Analysis","Analyze this Word document"),
(559,"DOCUMENT_EXCEL","Excel Analysis","Analyze this Excel file"),
(560,"DOCUMENT_OSINT","Comprehensive Document OSINT","Run full OSINT on this document"),
(561,"GPS","GPS Analysis","Analyze GPS coordinates"),
(562,"MAPS","Map Analysis","Analyze this map"),
(563,"STREET_VIEW","Street View","Show street view of this location"),
(564,"TERRAIN","Terrain Analysis","Analyze the terrain at this location"),
(565,"WEATHER","Weather at Location","What's the weather at this location?"),
(566,"DEMOGRAPHICS","Demographics at Location","What are the demographics of this area?"),
(567,"HISTORY","Historical Location","What is the history of this location?"),
(568,"SATELLITE","Satellite Imagery","Get satellite imagery of this location"),
(569,"GEOSPATIAL","Geospatial Analysis","Analyze geospatial data for this area"),
(570,"LOCATION_OSINT","Comprehensive Location OSINT","Run full OSINT on this location"),
(571,"DARK_ONION","Onion Sites","Search for this topic on onion sites"),
(572,"DARK_SCAN","Dark Web Scan","Scan the dark web for this domain"),
(573,"DARK_LEAKS","Data Leak Search","Search for leaks on the dark web"),
(574,"DARK_CREDENTIALS","Credential Search","Search for leaked credentials"),
(575,"DARK_FORUMS","Dark Web Forums","Search dark web forums"),
(576,"DARK_MARKETS","Dark Web Markets","Search dark web markets"),
(577,"DARK_CRYPTO","Crypto Tracking","Trace cryptocurrency transactions"),
(578,"DARK_ANALYTICS","Dark Web Analytics","Analyze dark web activity"),
(579,"DARK_MONITOR","Dark Web Monitoring","Monitor the dark web for threats"),
(580,"DARK_OSINT","Comprehensive Dark Web OSINT","Run full OSINT on the dark web"),
(581,"LINK_ANALYSIS","Link Analysis","Analyze connections between these data points"),
(582,"PATTERN","Pattern Recognition","Find patterns in this data"),
(583,"ANOMALY","Anomaly Detection","Detect anomalies in this data"),
(584,"CORRELATION","Correlation Analysis","Find correlations in this data"),
(585,"PREDICTIVE","Predictive OSINT","Predict future events based on data"),
(586,"SENTIMENT","Sentiment Analysis","Analyze sentiment in this text"),
(587,"NETWORK","Network Analysis","Analyze relationships in this network"),
(588,"TIMELINE","Timeline Analysis","Create a timeline of events"),
(589,"GEOGRAPHIC","Geographic Analysis","Analyze geographic patterns"),
(590,"PREDICTIVE_ANALYTICS","Predictive Analytics","Predict outcomes based on OSINT data"),
(591,"REPORT","OSINT Report Generation","Generate an OSINT report"),
(592,"VISUALIZE","Data Visualization","Visualize this OSINT data"),
(593,"DASHBOARD","OSINT Dashboard","Create an OSINT dashboard"),
(594,"MAP","OSINT Mapping","Map OSINT findings"),
(595,"TIMELINE","OSINT Timeline","Create an OSINT timeline"),
(596,"SUMMARY","OSINT Summary","Summarize OSINT findings"),
(597,"INTELLIGENCE","Intelligence Briefing","Create an intelligence briefing"),
(598,"ALERT","OSINT Alert","Set up OSINT alerts"),
(599,"MONITOR","OSINT Monitoring","Monitor OSINT data"),
(600,"ARCHIVE","OSINT Archive","Archive OSINT findings"),
]
